name = "meroxdotdev"
compatibility_date = "2026-01-20"
main = "./src/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

# KV namespace binding for reactions
[[kv_namespaces]]
binding = "REACTIONS_KV"
id = "0a2710e93af14c73862037ddd09b6659"
